### ISSUE TITLE
about NVF

### ISSUE THREAD

**Issue by xishuxishu** [Ysz2022/NVEdit#3]
Hello, great work! I'd like to understand whether the final video frames inferred by NVF are of the same length as the original video. If they are, does it mean we still need to generate each frame using the diffusion model? Can I understand it this way: first, use the I2T edit model to edit each frame of the video individually, and then NVF acts as a fine-tuner for the generated edited video to make it more coherent.

**Comment by Ysz2022** [comment]
The final video frames inferred by NVF are of the same length as the original video.
But during the second training stage, you do not need to edit each frames of the original video. You can randomly select half or a quarter of the frames and edit them and use them as the pseudo-GT. The final NVF trained in this way also exhibits coherent editing effect across the whole video, even it has not seen other edited frames.

**Comment by Ysz2022** [comment]
For example, there is a 100 frame video. During the field editing stage, you can edit and train all frames, or only select 50 of them. However, when selecting 50 frames, you need to set twice the number of iterations because the total number of iterations required is constant.

**Comment by xishuxishu** [comment]
> For example, there is a 100 frame video. During the field editing stage, you can edit and train all frames, or only select 50 of them. However, when selecting 50 frames, you need to set twice the number of iterations because the total number of iterations required is constant.

thanks for your reply.
Can I understand it this way: using the T2I editor to edit certain keyframes in the video, and then using NVF to model these keyframes to complete the video interpolation.

**Comment by Ysz2022** [comment]
It is also inaccurate to explain it by interpolation. In fact, after video fitting stage, NVF has known video info. We can dube the feature domain of NVF as A, which is also consistent with the original video, and dube the feature domain of edited video as B. Then in the field editing stage, NVF learns editing effect by 'looking' some edited frames. So even only editing part of frames (i.e., select some samples from domain B), NVF can also be updated towards the editing effect and thereby moving from the domain A to domain B.

**Comment by xishuxishu** [comment]
> 用插值来解释也是不准确的。事实上，在视频拟合阶段之后，NVF已经知道了视频信息。我们可以将NVF的特征域dube为A，这也与原始视频一致，并将编辑视频的特征域Dube为B。然后在现场编辑阶段，NVF通过“查看”一些编辑的帧来学习编辑效果。因此，即使只编辑部分帧（即从域 B 中选择一些样本），NVF 也可以更新为编辑效果，从而从域 A 移动到域 B。

Understood. So, I would like to ask, what would be the experimental results if we rely solely on the second stage to fit the edited frames without the first stage?

**Comment by Ysz2022** [comment]
I have attempted it at initial experiment and found that NVF cannot learn clear visual results. This is because for the t-th frame of a video, the T2I editing method generates different results at different iteration, so the pseudo-GTs are changing across iterations. Without the primitive prior learned in the first stage, NVF cannot learn effective info.

**Comment by xishuxishu** [comment]
I understand . thanks for your reply.
